apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mysqldata-equipos
  name: mysqldata-equipos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
