apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: pgdata-reportes
  name: pgdata-reportes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
