server:
  port: ${PORT:8888}

spring:
  application:
    name: SoftCorp-MicroServiceConfig
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # Sirve los .yaml de cada microservicio desde el classpath.
          search-locations: classpath:/configurations/
