server:
  port: 8761

spring:
  application:
    name: SoftCorp-MicroServiceEureka

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
