server:
  port: 8080

spring:
  application:
    name: SoftCorp-MicroServiceGateway
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - AddRequestHeader=X-Gateway-Request, true
          discovery:
            locator:
              enabled: true
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns:
                  - "http://localhost:*"
                  - "https://softcorp.netlify.app"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
          routes:
            - id: usuarios
              uri: lb://SOFTCORP-MICROSERVICEUSUARIOS
              predicates:
                - Path=/usuarios,/usuarios/**
              filters:
                - RewritePath=^/usuarios(?<segment>.*)$, /api/usuarios${segment}
            - id: tecnicos
              uri: lb://SOFTCORP-MICROSERVICEUSUARIOS
              predicates:
                - Path=/tecnicos,/tecnicos/**
              filters:
                - RewritePath=^/tecnicos(?<segment>.*)$, /api/tecnicos${segment}
            - id: equipos
              uri: lb://SOFTCORP-MICROSERVICEEQUIPOS
              predicates:
                - Path=/equipos,/equipos/**
              filters:
                - RewritePath=^/equipos(?<segment>.*)$, /api/equipos${segment}
            - id: incidencias
              uri: lb://SOFTCORP-MICROSERVICEINCIDENCIAS
              predicates:
                - Path=/incidencias,/incidencias/**
              filters:
                - RewritePath=^/incidencias(?<segment>.*)$, /api/incidencias${segment}
            - id: repuestos
              uri: lb://SOFTCORP-MICROSERVICEINCIDENCIAS
              predicates:
                - Path=/repuestos,/repuestos/**
              filters:
                - RewritePath=^/repuestos(?<segment>.*)$, /api/repuestos${segment}
            - id: informes
              uri: lb://SOFTCORP-MICROSERVICEINCIDENCIAS
              predicates:
                - Path=/informes,/informes/**
              filters:
                - RewritePath=^/informes(?<segment>.*)$, /api/informes${segment}
            - id: diccionario-fallas
              uri: lb://SOFTCORP-MICROSERVICEDICCIONARIOFALLAS
              predicates:
                - Path=/diccionario-fallas,/diccionario-fallas/**
              filters:
                - RewritePath=^/diccionario-fallas(?<segment>.*)$, /api/diccionario-fallas${segment}
            - id: reportes
              uri: lb://SOFTCORP-MICROSERVICEREPORTES
              predicates:
                - Path=/reportes,/reportes/**
              filters:
                - RewritePath=^/reportes(?<segment>.*)$, /api/reportes${segment}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
